# Generated by Django 3.2.4 on 2021-06-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uip', models.CharField(max_length=20)),
                ('q', models.IntegerField()),
                ('a', models.TextField()),
            ],
        ),
    ]
